version: '3.9'

services:
  # 🔗 Django backend
  backend:
    build:
      context: ./blocktrack_backend
    container_name: blocktrack_backend
    volumes:
      - ./blocktrack_backend:/app
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    depends_on:
      - blocktrack_postgres
      - ipfs
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1

  # 🌐 Angular frontend
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "${FRONTEND_PORT:-4200}:4200"
    env_file:
      - .env
    environment:
      - NODE_ENV=development

  # 🗃️ PostgreSQL database
  blocktrack_postgres:
    image: postgres:15
    container_name: blocktrack_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-blockuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-blockpass}
      POSTGRES_DB: ${POSTGRES_DB:-blocktrack_db}
    ports:
      - "${POSTGRES_PORT:-15433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 🧪 Adminer UI
  adminer:
    image: adminer
    container_name: blocktrack_adminer
    restart: always
    ports:
      - "${ADMINER_PORT:-8081}:8080"
    depends_on:
      - blocktrack_postgres

  # 🧿 IPFS node
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs_node
    ports:
      - "${IPFS_API_PORT:-5001}:5001"
      - "${IPFS_GATEWAY_PORT:-8080}:8080"
      - "${IPFS_SWARM_PORT:-4001}:4001"
    volumes:
      - ipfs_staging:/export
      - ipfs_data:/data/ipfs

  kafka_broker:
    image: bitnami/kafka:3.5
    container_name: kafka_broker
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_broker:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kafka_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - kafka_zookeeper

  kafka_zookeeper:
    image: bitnami/zookeeper:latest
    container_name: kafka_zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes


volumes:
  postgres_data:
  ipfs_data:
  ipfs_staging:
